[Unit]
Wants=zerotier-one.service
After=zerotier-one.service
StartLimitIntervalSec=0

[Service]
ExecCondition=/usr/local/sbin/sea-speed-nginx-zerotier-wait
Restart=on-failure
RestartSec=10s
TimeoutStartSec=130s
